### ISSUE TITLE
Seek doesn't work

### ISSUE THREAD

**Issue by iparr** [mopidy/mopidy-beets#12]
Unfortunately it just goes quiet.

```
ERROR    Could not perform seek on resource. Debug message: gstsouphttpsrc.c(874): gst_soup_http_src_got_headers_cb (): /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin10/GstSoupHTTPSrc:source:
Server does not accept Range HTTP header, URL: http://pr0:8337/item/35570/file
```

This is another way in which mopidy doesn't treat beets originating music as a 'first class citizen', including being unable to display things as albums or as artists in web clients like *Musicbox* or the default client.

Are these things related and is it too ambitious for beets music to be perfectly integrated with local music?

**Comment by sumpfralle** [comment]
Hi iparr,
the URL you posted above (http://pr0:8337/item/35570/file) looks like a URL from Beets' web api plugin. In this case it would be an issue of that plugin, or?

If it is indeed an issue of the beets plugin for mopidy: could you write down a curl request that exposes the issue? This will allow me to reproduce it.

**Comment by iparr** [comment]
I'm afraid it's no longer returning that error. After updating Mopidy and the plugins I'm unable to find music to play and no errors are displayed. Nothing is working at all so I'm unable to help you.

**Comment by sumpfralle** [comment]
Gstreamer seems to require "seeking" for certain filetypes (e.g. OGG files): Gstreamer uses HTTP requests with a "Range" header for this purpose. Sadly the Beets web API does not support this header.

See the [README](https://github.com/mopidy/mopidy-beets#proxy-configuration-for-ogg-files-optionall) for hints regarding an http proxy (e.g. Nginx) between Mopidy and Beets in order to solve this issue.
